workflows:
  ios-project-debug:
    name: iOS Debug Build & Test
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "NextPatch.xcworkspace"
        XCODE_SCHEME: "NextPatch"
    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods --no-document
          pod repo update
          pod install --repo-update

      - name: Run tests
        script: |
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
          clean build test \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Build debug app
        script: |
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - arifa.aja16@gmail.com
